# Generated by Django 4.2.11 on 2025-02-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bgtask", "0002_backgroundtask_namespace_alter_backgroundtask_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundtask",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
