# Generated by Django 4.2.11 on 2024-03-08 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelWithBackgroundActions",
            fields=[
                ("id", models.UUIDField( editable=False, default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("text", models.TextField(blank=True, default="")),
            ],
        ),
    ]
