# Generated by Django 4.2.11 on 2024-04-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelwithbackgroundactions",
            options={"verbose_name": "Models with background action"},
        ),
    ]
